### ISSUE TITLE
Please make a Linux variant

### ISSUE THREAD

**Issue by Eduarch42** [davidferguson/pibakery#110]
It would be awesome if a Linux variant of pibakery could be available 
Cheers

**Comment by davidferguson** [comment]
To give an update about Linux support:

PiBakery v2 should add in Linux support so that it "just works" on Linux as well as Windows and Mac.

However, currently you'll need to manually install `kpartx` for PiBakery v2 to work.

When I make an installer for Linux, I'll try and bundle kpartx in or list it as a dependency, so that it's installed for PiBakery.

I'm closing this for now, as Linux support *is* implemented, all that's left is the installer for it.
