### ISSUE TITLE
No macOS pkg of 0.3.8

### ISSUE THREAD

**Issue by sanyer** [davidferguson/pibakery#136]
There is no `PiBakery.pkg` asset available for version 0.3.8

**Comment by davidferguson** [comment]
Not in the GitHub releases, no. This is because as Raspbian has become larger and larger, the Mac installer (which uses zip compression) is too large to be uploaded to GitHub releases. The Windows installer, which uses 7zip compression, still just fits.

I know self-host the Mac installer, which you can download from http://pibakery.org/docs/install-mac.html

**Comment by sanyer** [comment]
ok, thanks for the answer ;-)
