### ISSUE TITLE
Run Command block doesn't work?

### ISSUE THREAD

**Issue by electronicwhisper** [davidferguson/pibakery#19]
I am having trouble getting a "Run Command" block within an "On First Boot" section to run. All the other blocks I have tried, including "Download file" work. I made a Run Command as simple as

![image](https://cloud.githubusercontent.com/assets/177466/18396274/aabc7c6e-7677-11e6-8a9a-24a924877d98.png)

But the test.txt file doesn't seem to be created. Any ideas?

Thanks! The tool is great!

**Comment by davidferguson** [comment]
Thanks for reporting that - I've found the fault and [edited the file](https://github.com/davidferguson/pibakery-blocks/commit/71d586a9265da5b6ef64135378470105c25e3e4f) in the runcommand block. This will be fixed in PiBakery when I next push out a block update, which will be very soon.

If you want to get the update straight away, just edit the file locally (found in `C:\Program Files\PiBakery\resources\pibakery-block\runcommand\` on Windows and `/Applications/PiBakery.app/Contents/resources/app/pibakery-blocks/runcommand` on Mac).
