### ISSUE TITLE
No available images.json file

### ISSUE THREAD

**Issue by crow1170** [davidferguson/pibakery#39]
The ReadMe says:

> Lastly you'll need to create a file images.json inside the os folder which tells PiBakery which operating systems you have installed and available for use. Download the example file from **not-created-yet**, save it as images.json into the os folder where you stored the .img files, and then change the values of the installed paramater for each of the operating systems depending on which ones you have installed.

what is the structure of this file? How does it relate to the `info.json` file present at that location?

**Comment by davidferguson** [comment]
The main (and really only) way it changes is that is supports multiple .img files. You can see the current formate at https://gist.github.com/davidferguson/249b28f3e41d6e9e69f8a5314320c913 but this could change over the next day or two as I finalise changes with it.

I hope to release PiBakery 0.3.0 which will user images.json rather than info.json very soon - maybe even today.
